package com.ejustech.iron.common;

public class IronEnum {
	public enum LoginCheckResult {
		OK, USER_ID_IS_EMPTY, USER_PASSWORD_IS_EMPTY, ALL_ITEMS_IS_EMPTY, USER_ID_NOT_FOUND, USER_ID_NOT_ROLE, USER_PASSWORD_IS_ERROR
	}

	public enum TableName {
		M_USER, T_IRON_INFO
	}

	public enum ValidateStatusInputByNew {
		EMPTY_YearMonthDay,
		EMPTY_QiHao,
		EMPTY_LuCi,
		EMPTY_JunPinFlg,
		EMPTY_GuiGe,
		EMPTY_ShengChanLuHao,
		EMPTY_FanYingQiHao,
		EMPTY_ShiYongCiShu,
		EMPTY_Mg,
		EMPTY_TiCl4,
		EMPTY_MaoZhong,
		EMPTY_JingZhong,
		EMPTY_ChengPinLv,
		EMPTY_YuanSuFe,
		EMPTY_YuanSuSi,
		EMPTY_YuanSuCl,
		EMPTY_YuanSuC,
		EMPTY_YuanSuN,
		EMPTY_YuanSuO,
		EMPTY_YuanSuH,
		EMPTY_YuanSuMn,
		EMPTY_YuanSuHb,
		EMPTY_DengJiHanMeng,
		EMPTY_KaoHeDengJiChuMeng,
		EMPTY_GongYiTiaoZheng,
		EMPTY_GongYiShiYan,
		EMPTY_DiPiKg,
		EMPTY_ShangMaoKg,
		EMPTY_PaBiKg,
		EMPTY_FeiDiPiKg,
		EMPTY_FeiShangMaoKg,
		EMPTY_FeiPaBiKg,
		EMPTY_FeiTaiFenKg,
		EMPTY_CiYuanKg,
		EMPTY_ShouXuanFeiLiaoKg,
		EMPTY_SunHaoKg,
		EMPTY_ZongPaiMeiLiangKg,
		EMPTY_ChuLuZhenKongDu,
		EMPTY_YuanZuiGaoWenDu,
		EMPTY_ZhengLiuGaoHengDian,
		EMPTY_ZhuanZhengLiu,
		EMPTY_JiaShouCi,
		EMPTY_JiaMoCi,
		EMPTY_TongDao,
		EMPTY_ShengChanGuZhang,
		EMPTY_BeiZhuShuoMing,
		LENGTH_YearMonthDay,
		LENGTH_QiHao,
		LENGTH_LuCi,
		LENGTH_JunPinFlg,
		LENGTH_GuiGe,
		LENGTH_ShengChanLuHao,
		LENGTH_FanYingQiHao,
		LENGTH_ShiYongCiShu,
		LENGTH_Mg,
		LENGTH_TiCl4,
		LENGTH_MaoZhong,
		LENGTH_JingZhong,
		LENGTH_ChengPinLv,
		LENGTH_YuanSuFe,
		LENGTH_YuanSuSi,
		LENGTH_YuanSuCl,
		LENGTH_YuanSuC,
		LENGTH_YuanSuN,
		LENGTH_YuanSuO,
		LENGTH_YuanSuH,
		LENGTH_YuanSuMn,
		LENGTH_YuanSuHb,
		LENGTH_DengJiHanMeng,
		LENGTH_KaoHeDengJiChuMeng,
		LENGTH_GongYiTiaoZheng,
		LENGTH_GongYiShiYan,
		LENGTH_DiPiKg,
		LENGTH_ShangMaoKg,
		LENGTH_PaBiKg,
		LENGTH_FeiDiPiKg,
		LENGTH_FeiShangMaoKg,
		LENGTH_FeiPaBiKg,
		LENGTH_FeiTaiFenKg,
		LENGTH_CiYuanKg,
		LENGTH_ShouXuanFeiLiaoKg,
		LENGTH_SunHaoKg,
		LENGTH_ZongPaiMeiLiangKg,
		LENGTH_ChuLuZhenKongDu,
		LENGTH_YuanZuiGaoWenDu,
		LENGTH_ZhengLiuGaoHengDian,
		LENGTH_ZhuanZhengLiu,
		LENGTH_JiaShouCi,
		LENGTH_JiaMoCi,
		LENGTH_TongDao,
		LENGTH_ShengChanGuZhang,
		LENGTH_BeiZhuShuoMing,
		FORMAT_DATE,
		FORMAT_NUMBER
	}
}