/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ejustech.iron.databean.form;

public class Result2FormBean {
	/*
	 * Generated fields
	 */

	/** n property */
	private String n;

	/** o property */
	private String o;

	/** hb property */
	private String hb;

	/** fe property */
	private String fe;

	/** qihao property */
	private String qihao;

	/** cl property */
	private String cl;
	
	/** zonglushu property */
	private String zonglushu;
	
	private String zongmaozhong;
	private String junmaozhong;
	private String junmgdanhao;
	private String junhuishoulv;
	private String zongjingzhong;
	private String junjingzhong;
	private String j0Aji;
	private String j0Ajilv;
	private String j0ji;
	private String j0jilv;
	private String j0jiyishang;
	private String j1ji;
	private String j1jilv;
	private String j2ji;
	private String j3ji;
	private String j4ji;
	private String j5ji;
	private String j2jijiyixia;
	private String j2jijiyixialv;
	
	/**
	 * Returns the c.
	 * 
	 * @return String
	 */
	public String getZongmaozhong() {
		return zongmaozhong;
	}

	/**
	 * Set the c.
	 * 
	 * @param c
	 *            The c to set
	 */
	public void setZongmaozhong(String zongmaozhong) {
		this.zongmaozhong = zongmaozhong;
	}

	/**
	 * Returns the n.
	 * 
	 * @return String
	 */
	public String getN() {
		return n;
	}

	/**
	 * Set the n.
	 * 
	 * @param n
	 *            The n to set
	 */
	public void setN(String n) {
		this.n = n;
	}

	/**
	 * Returns the o.
	 * 
	 * @return String
	 */
	public String getO() {
		return o;
	}

	/**
	 * Set the o.
	 * 
	 * @param o
	 *            The o to set
	 */
	public void setO(String o) {
		this.o = o;
	}

	/**
	 * Returns the hb.
	 * 
	 * @return String
	 */
	public String getHb() {
		return hb;
	}

	/**
	 * Set the hb.
	 * 
	 * @param hb
	 *            The hb to set
	 */
	public void setHb(String hb) {
		this.hb = hb;
	}

	/**
	 * Returns the fe.
	 * 
	 * @return String
	 */
	public String getFe() {
		return fe;
	}

	/**
	 * Set the fe.
	 * 
	 * @param fe
	 *            The fe to set
	 */
	public void setFe(String fe) {
		this.fe = fe;
	}

	/**
	 * Returns the qihao.
	 * 
	 * @return String
	 */
	public String getQihao() {
		return qihao;
	}

	/**
	 * Set the qihao.
	 * 
	 * @param qihao
	 *            The qihao to set
	 */
	public void setQihao(String qihao) {
		this.qihao = qihao;
	}

	/**
	 * Returns the cl.
	 * 
	 * @return String
	 */
	public String getCl() {
		return cl;
	}

	/**
	 * Set the cl.
	 * 
	 * @param cl
	 *            The cl to set
	 */
	public void setCl(String cl) {
		this.cl = cl;
	}
	
	
	
	/**
	 * Returns the cl.
	 * 
	 * @return String
	 */
	public String getZonglushu() {
		return zonglushu;
	}

	/**
	 * Set the cl.
	 * 
	 * @param cl
	 *            The cl to set
	 */
	public void setZonglushu(String zonglushu) {
		this.zonglushu = zonglushu;
	}

	public String getJunmaozhong() {
		return junmaozhong;
	}

	public void setJunmaozhong(String junmaozhong) {
		this.junmaozhong = junmaozhong;
	}

	public String getJunmgdanhao() {
		return junmgdanhao;
	}

	public void setJunmgdanhao(String junmgdanhao) {
		this.junmgdanhao = junmgdanhao;
	}

	public String getJunhuishoulv() {
		return junhuishoulv;
	}

	public void setJunhuishoulv(String junhuishoulv) {
		this.junhuishoulv = junhuishoulv;
	}

	public String getZongjingzhong() {
		return zongjingzhong;
	}

	public void setZongjingzhong(String zongjingzhong) {
		this.zongjingzhong = zongjingzhong;
	}

	public String getJunjingzhong() {
		return junjingzhong;
	}

	public void setJunjingzhong(String junjingzhong) {
		this.junjingzhong = junjingzhong;
	}

	public String getJ0Aji() {
		return j0Aji;
	}

	public void setJ0Aji(String j0Aji) {
		this.j0Aji = j0Aji;
	}

	public String getJ0Ajilv() {
		return j0Ajilv;
	}

	public void setJ0Ajilv(String j0Ajilv) {
		this.j0Ajilv = j0Ajilv;
	}

	public String getJ0ji() {
		return j0ji;
	}

	public void setJ0ji(String j0ji) {
		this.j0ji = j0ji;
	}

	public String getJ0jilv() {
		return j0jilv;
	}

	public void setJ0jilv(String j0jilv) {
		this.j0jilv = j0jilv;
	}

	public String getJ0jiyishang() {
		return j0jiyishang;
	}

	public void setJ0jiyishang(String j0jiyishang) {
		this.j0jiyishang = j0jiyishang;
	}

	public String getJ1ji() {
		return j1ji;
	}

	public void setJ1ji(String j1ji) {
		this.j1ji = j1ji;
	}

	public String getJ1jilv() {
		return j1jilv;
	}

	public void setJ1jilv(String j1jilv) {
		this.j1jilv = j1jilv;
	}

	public String getJ2ji() {
		return j2ji;
	}

	public void setJ2ji(String j2ji) {
		this.j2ji = j2ji;
	}

	public String getJ3ji() {
		return j3ji;
	}

	public void setJ3ji(String j3ji) {
		this.j3ji = j3ji;
	}

	public String getJ4ji() {
		return j4ji;
	}

	public void setJ4ji(String j4ji) {
		this.j4ji = j4ji;
	}

	public String getJ5ji() {
		return j5ji;
	}

	public void setJ5ji(String j5ji) {
		this.j5ji = j5ji;
	}

	public String getJ2jijiyixia() {
		return j2jijiyixia;
	}

	public void setJ2jijiyixia(String j2jijiyixia) {
		this.j2jijiyixia = j2jijiyixia;
	}

	public String getJ2jijiyixialv() {
		return j2jijiyixialv;
	}

	public void setJ2jijiyixialv(String j2jijiyixialv) {
		this.j2jijiyixialv = j2jijiyixialv;
	}
}