/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 * 总输出表
 */
package com.ejustech.iron.databean.form;

public class Result2FormBean {
	/*
	 * Generated fields
	 */

	/** c property */
	private String c;

	/** n property */
	private String n;

	/** o property */
	private String o;

	/** hb property */
	private String hb;

	/** fe property */
	private String fe;

	/** qihao property */
	private String qihao;

	/** cl property */
	private String cl;

	

	/*
	 * Generated Methods
	 */

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	// public void reset(ActionMapping mapping, HttpServletRequest request) {
	// // TODO Auto-generated method stub
	// map.clear();
	// }	
	
	/**
	 * Returns the c.
	 * 
	 * @return String
	 */
	public String getC() {
		return c;
	}

	/**
	 * Set the c.
	 * 
	 * @param c
	 *            The c to set
	 */
	public void setC(String c) {
		this.c = c;
	}

	/**
	 * Returns the n.
	 * 
	 * @return String
	 */
	public String getN() {
		return n;
	}

	/**
	 * Set the n.
	 * 
	 * @param n
	 *            The n to set
	 */
	public void setN(String n) {
		this.n = n;
	}

	/**
	 * Returns the o.
	 * 
	 * @return String
	 */
	public String getO() {
		return o;
	}

	/**
	 * Set the o.
	 * 
	 * @param o
	 *            The o to set
	 */
	public void setO(String o) {
		this.o = o;
	}

	/**
	 * Returns the hb.
	 * 
	 * @return String
	 */
	public String getHb() {
		return hb;
	}

	/**
	 * Set the hb.
	 * 
	 * @param hb
	 *            The hb to set
	 */
	public void setHb(String hb) {
		this.hb = hb;
	}

	/**
	 * Returns the fe.
	 * 
	 * @return String
	 */
	public String getFe() {
		return fe;
	}

	/**
	 * Set the fe.
	 * 
	 * @param fe
	 *            The fe to set
	 */
	public void setFe(String fe) {
		this.fe = fe;
	}

	/**
	 * Returns the qihao.
	 * 
	 * @return String
	 */
	public String getQihao() {
		return qihao;
	}

	/**
	 * Set the qihao.
	 * 
	 * @param qihao
	 *            The qihao to set
	 */
	public void setQihao(String qihao) {
		this.qihao = qihao;
	}

	/**
	 * Returns the cl.
	 * 
	 * @return String
	 */
	public String getCl() {
		return cl;
	}

	/**
	 * Set the cl.
	 * 
	 * @param cl
	 *            The cl to set
	 */
	public void setCl(String cl) {
		this.cl = cl;
	}
}