/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ejustech.iron.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.actions.EventDispatchAction;

import com.ejustech.iron.business.InputByNewBusiness;
import com.ejustech.iron.databean.form.InputByNewFormBean;
import com.ejustech.iron.form.InputByNewForm;

/**
 * MyEclipse Struts Creation date: 04-19-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/inputByNew" name="inputByNewForm"
 *                input="/form/inputByNew.jsp" scope="request" validate="true"
 */
public class InputByNewAction extends EventDispatchAction {
	// 处理保存的动作
	public ActionForward Save(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {

		if (request.getSession().getAttribute("logout") != null) {
			return mapping.findForward("relogin");
		}

		InputByNewForm inputByNewForm = (InputByNewForm) form;
		InputByNewBusiness business = new InputByNewBusiness();

		try {
			business.Save(inputByNewForm);

			ArrayList<InputByNewFormBean> initList = business.initInputByNewForm();
			inputByNewForm.setInputByNewList(initList);
			inputByNewForm.setRole("1");

			return mapping.findForward("OK");
		} catch (Exception e) {
			ActionErrors error = new ActionErrors();
			error.add("errors", new ActionMessage("error.inputByNew.insertError", e.toString()));
			this.saveErrors(request, error);
			inputByNewForm.setRole("1");
			return mapping.findForward("NG");
		}
	}

	// 处理保存的动作
	public ActionForward Reset(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		try {
			if (request.getSession().getAttribute("logout") != null) {
				return mapping.findForward("relogin");
			}

			InputByNewForm inputByNewForm = (InputByNewForm) form;
			InputByNewBusiness business = new InputByNewBusiness();

			ArrayList<InputByNewFormBean> initList = business.initInputByNewForm();

			inputByNewForm.setInputByNewList(initList);

			inputByNewForm.setRole("1");
			return mapping.findForward("OK");
		} catch (Exception e) {
		}
		return null;
	}

	// 处理返回跳转动作
	public ActionForward back(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		try {
			if (request.getSession().getAttribute("logout") != null) {
				return mapping.findForward("relogin");
			}

			return mapping.findForward("back");
		} catch (Exception e) {
			e.printStackTrace();
			return mapping.findForward("searchError");
		}
	}
}