/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ejustech.iron.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.EventDispatchAction;

import com.ejustech.iron.business.InputByNewBusiness;
import com.ejustech.iron.form.InputByNewForm;

/**
 * MyEclipse Struts Creation date: 04-19-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/inputByNew" name="inputByNewForm"
 *                input="/form/inputByNew.jsp" scope="request" validate="true"
 */
public class InputByNewAction extends EventDispatchAction {
	// 处理保存的动作
	public ActionForward Save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try {
			if (request.getSession().getAttribute("logout") != null) {return mapping.findForward("relogin");}
			InputByNewForm inputByNewForm = (InputByNewForm) form;
			InputByNewBusiness business = new InputByNewBusiness();
			
			inputByNewForm.setSave(true);
			business.Save(inputByNewForm);
			
			return mapping.findForward("OK");
		} catch (Exception e) {
		}
		return null;
	}
	
	// 处理保存的动作
	public ActionForward Commit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try {
			if (request.getSession().getAttribute("logout") != null) {return mapping.findForward("relogin");}
			InputByNewForm inputByNewForm = (InputByNewForm) form;
			InputByNewBusiness business = new InputByNewBusiness();
			inputByNewForm.setSave(false);
			business.Commit(inputByNewForm);
			
			return mapping.findForward("OK");
		} catch (Exception e) {
		}
		return null;
	}	
}