/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ejustech.iron.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ejustech.iron.form.Result6Form;

/** 
 * MyEclipse Struts
 * Creation date: 04-17-2013
 * 
 * XDoclet definition:
 * @struts.action path="/result1" name="result1Form" input="/form/result1.jsp" scope="request" validate="true"
 */
public class Result6Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Result6Form result6Form = (Result6Form) form;// TODO Auto-generated method stub
		return null;
	}
}