/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ejustech.iron.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.EventDispatchAction;

import com.ejustech.iron.databean.form.SearchFormBean;

/** 
 * MyEclipse Struts
 * Creation date: 04-17-2013
 * 
 * XDoclet definition:
 * @struts.action path="/result1" name="result1Form" input="/form/result1.jsp" scope="request" validate="true"
 */
public class Result1Action extends EventDispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	// 处理search动作
	public ActionForward search(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try {
			SearchFormBean searchFormBean = new SearchFormBean();
			
			searchFormBean.setSelInfoList("1");
			ArrayList<SearchFormBean> selList = new ArrayList<SearchFormBean>();
			selList.add(searchFormBean);
			request.setAttribute("SELLIST", selList);

//			Result1Form result1Form = (Result1Form)form;
//			SearchForm searchForm = (SearchForm) form;
//			System.out.println("llll = " + result1Form.getIndexCheckbox().length);
//			String[] indexValue = result1Form.getIndexCheckbox();
//			StringBuffer transmode = new StringBuffer("");
//			String[] trans = indexValue;
//			if (trans != null && trans.length > 0) {
//				for (int i = 0; i < trans.length; i++) {
//					transmode.append(trans[i]);
//					if (!(i == trans.length - 1)) {
//						transmode.append(",");
//					}
//				}
//			}
//			System.out.println("indexValue = " + transmode.toString());
			
			return mapping.findForward("search");
		} catch (Exception e) {
		}
		return null;
	}
}