/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cc.flyzz.sample;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-18-2013
 * 
 * XDoclet definition:
 * @struts.action path="/sampleQueryResult" name="sampleQueryResultForm" input="/jsp/sampleQueryResult.jsp" scope="request" validate="true"
 */
public class SampleQueryResultAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SampleQueryResultForm sampleQueryResultForm = (SampleQueryResultForm) form;// TODO Auto-generated method stub
		return null;
	}
}