/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ejustech.iron.form;

import java.util.List;

import org.apache.struts.action.ActionForm;

import com.ejustech.iron.common.AutoArrayList;
import com.ejustech.iron.databean.form.InputByNewFormBean;

public class InputByNewForm extends ActionForm {
	private List inputByNewList = new AutoArrayList(InputByNewFormBean.class);

	public List getInputByNewList() {
		return inputByNewList;
	}

	public void setInputByNewList(List inputByNewList) {
		this.inputByNewList = inputByNewList;
	}
}