/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ejustech.iron.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.ejustech.iron.business.InputByNewBusiness;
import com.ejustech.iron.business.InputByUpdateBusiness;
import com.ejustech.iron.common.AutoArrayList;
import com.ejustech.iron.common.StringHelper;
import com.ejustech.iron.common.IronEnum.ErrorType;
import com.ejustech.iron.common.IronEnum.UserRole;
import com.ejustech.iron.common.IronEnum.ValidateStatusInput;
import com.ejustech.iron.databean.form.InputByNewFormBean;
import com.ejustech.iron.databean.form.InputByUpdateFormBean;

/** 
 * MyEclipse Struts
 * Creation date: 05-26-2013
 * 
 * XDoclet definition:
 * @struts.form name="InputByUpdateForm"
 */
public class InputByUpdateForm extends ActionForm {
	private List inputByUpdateList = new AutoArrayList(InputByUpdateFormBean.class);
	private boolean isSave = true;
	private String role = "";
	
	/**
	 * @return the isSave
	 */
	public boolean isSave() {
		return isSave;
	}

	/**
	 * @param isSave the isSave to set
	 */
	public void setSave(boolean isSave) {
		this.isSave = isSave;
	}

	/**
	 * @return the role
	 */
	public String getRole() {
		return role;
	}

	/**
	 * @param role the role to set
	 */
	public void setRole(String role) {
		this.role = role;
	}
	
	public List getInputByUpdateList() {
		return inputByUpdateList;
	}

	public void setInputByUpdateList(List inputByUpdateList) {
		this.inputByUpdateList = inputByUpdateList;
	}
	
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
//		return null;
		InputByUpdateBusiness business = new InputByUpdateBusiness();
		InputByUpdateFormBean checkBean = new InputByUpdateFormBean();
		ArrayList<ValidateStatusInput> checkResultList = new ArrayList<ValidateStatusInput>();

		ActionErrors error = new ActionErrors();
		ValidateStatusInput checkResult;

		for (int rowIndex = 0; rowIndex < inputByUpdateList.size(); rowIndex++) {
			checkBean = (InputByUpdateFormBean) inputByUpdateList.get(rowIndex);
			
			if (StringHelper.isNullEmpty(checkBean.getLuCi()) && StringHelper.isNullEmpty(checkBean.getGuiGe())) continue;
			
			HttpSession session = request.getSession();
			
			if (isSave) {
				InputByUpdateBusiness x = new InputByUpdateBusiness();
				
				x.InputByUpdateForm2UTF8(checkBean);
				
				checkResultList.addAll(business.checkAllForSave(checkBean, UserRole.R3));
			}
			
//			if (request.getAttribute("SaveOrCommit").equals("Commit")) {
//				checkResultList.addAll(business.checkAllForCommit(checkBean, UserRole.R3));
//			}			
			
			for (int i = 0; i < checkResultList.size(); i++) {
				checkResult = checkResultList.get(i);

				if (checkResult != ValidateStatusInput.OK) {

					ErrorType errorType = business.getErrorType(checkResult);

					if (errorType == ErrorType.EMPTY) {
						error.add("errors", new ActionMessage("error.inputByNew.Empty", business.getItemNameByErrorStatus(checkResult),
								rowIndex + 1));
					} else if (errorType == ErrorType.LENGTH) {
						error.add("errors", new ActionMessage("error.inputByNew.Length", business.getItemNameByErrorStatus(checkResult),
								rowIndex + 1));
					} else if (errorType == ErrorType.NUMBER_FORMAT) {
						// TODO
						error.add("errors",
								new ActionMessage("error.inputByNew.NumberFormat", business.getItemNameByErrorStatus(checkResult),
										rowIndex + 1, 20));
					} else if (errorType == ErrorType.DATE_FORMAT) {
						error.add("errors", new ActionMessage("error.inputByNew.DateFormat", business.getItemNameByErrorStatus(checkResult),
								rowIndex + 1));
					}
				}
			}
		}

		return error;
	}

}